-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPC/t1xJOVKTF0iRt
2EqVcX+kyYInCgguRgBcxFvQVHKgCgYIKoZIzj0DAQehRANCAAQ/fvyj9BLCn9w1
Y9tufFYqxtk2a9am/1+cEqqP6x2gDaX8XtwhC0FznQj+NKeRZEeTeRxe9/NExlUh
+R1udzGm
-----END PRIVATE KEY-----